name: large_content_viewer
description: >-
  A Flutter widget that mimics the iOS Large Content Viewer behavior, showing a
  magnified view of its child on long-press, useful for accessibility large text
  sizes. Works on both iOS and Android.
version: 0.1.1
repository: https://github.com/MaElaRo/large_content_viewer

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
